PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?source ?projected_predicate ?bfo_target .
}
WHERE {
  FILTER(isIRI(?source))
  FILTER(
    STRSTARTS(STR(?source), "http://www.w3.org/ns/sosa/")
    || STRSTARTS(STR(?source), "http://www.w3.org/ns/ssn/")
  )

  {
    ?source rdfs:subClassOf ?bfo_target .
    FILTER(isIRI(?bfo_target))
    FILTER(STRSTARTS(STR(?bfo_target), "http://purl.obolibrary.org/obo/BFO_"))
    BIND(rdfs:subClassOf AS ?projected_predicate)
  }
  UNION
  {
    ?source rdfs:subPropertyOf ?bfo_target .
    FILTER(isIRI(?bfo_target))
    FILTER(STRSTARTS(STR(?bfo_target), "http://purl.obolibrary.org/obo/BFO_"))
    BIND(rdfs:subPropertyOf AS ?projected_predicate)
  }
  UNION
  {
    ?source rdfs:subClassOf ?cco_target .
    FILTER(isIRI(?cco_target))
    FILTER(STRSTARTS(STR(?cco_target), "https://www.commoncoreontologies.org/ont"))
    ?cco_target rdfs:subClassOf+ ?bfo_target .
    FILTER(isIRI(?bfo_target))
    FILTER(STRSTARTS(STR(?bfo_target), "http://purl.obolibrary.org/obo/BFO_"))
    BIND(rdfs:subClassOf AS ?projected_predicate)
  }
  UNION
  {
    ?source owl:equivalentClass ?cco_target .
    FILTER(isIRI(?cco_target))
    FILTER(STRSTARTS(STR(?cco_target), "https://www.commoncoreontologies.org/ont"))
    ?cco_target rdfs:subClassOf+ ?bfo_target .
    FILTER(isIRI(?bfo_target))
    FILTER(STRSTARTS(STR(?bfo_target), "http://purl.obolibrary.org/obo/BFO_"))
    BIND(rdfs:subClassOf AS ?projected_predicate)
  }
  UNION
  {
    ?source rdfs:subPropertyOf ?cco_target .
    FILTER(isIRI(?cco_target))
    FILTER(STRSTARTS(STR(?cco_target), "https://www.commoncoreontologies.org/ont"))
    ?cco_target rdfs:subPropertyOf+ ?bfo_target .
    FILTER(isIRI(?bfo_target))
    FILTER(STRSTARTS(STR(?bfo_target), "http://purl.obolibrary.org/obo/BFO_"))
    BIND(rdfs:subPropertyOf AS ?projected_predicate)
  }
}
