#!/usr/bin/env python3
"""Generate and validate the maintained SOSA-next modular products."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import tempfile
from collections import Counter
from dataclasses import replace
from pathlib import Path
from typing import Any, Callable, Mapping

from rdflib import Graph, URIRef
from rdflib.compare import isomorphic
from rdflib.namespace import OWL, RDF

import check_sosa_next_mapping as mapping_checker
import generate_mapping_from_coms as coms
import modular_products
import publication_metadata
from product_dispositions import (
    axiom_input_from_canonical_row,
    classify_target_category,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = REPO_ROOT / "mappings/SOSA-next-to-BFO-COMS.xlsx"
METADATA_PATH = REPO_ROOT / "config/publication-metadata.toml"

GENERATED_NOTICE = (
    "# Generated from mappings/SOSA-next-to-BFO-COMS.xlsx. "
    "Do not edit this file directly."
)

PRODUCT_ORDER = (
    "alignment_core",
    "strict_bfo_mapping",
    "cco_extension",
)

MAINTAINED_PRODUCTS = {
    "alignment_core": (
        REPO_ROOT
        / "releases/sosa-next/sosa-alignment-core.ttl"
    ),
    "strict_bfo_mapping": (
        REPO_ROOT
        / "releases/sosa-next/sosa-bfo-mapping.ttl"
    ),
    "cco_extension": (
        REPO_ROOT
        / "releases/sosa-next/sosa-cco-extension.ttl"
    ),
}

CURRENT_SOSA_PRODUCTS = {
    "integrated": REPO_ROOT / "SSN2BFO.ttl",
    "alignment_core": (
        REPO_ROOT
        / "releases/current-ssn-sosa/"
        "ssn-sosa-alignment-core.ttl"
    ),
    "strict_bfo_mapping": (
        REPO_ROOT
        / "releases/current-ssn-sosa/"
        "ssn-sosa-bfo-mapping.ttl"
    ),
    "bfo_projection": (
        REPO_ROOT
        / "releases/current-ssn-sosa/"
        "ssn-sosa-bfo-projection.ttl"
    ),
    "cco_extension": (
        REPO_ROOT
        / "releases/current-ssn-sosa/"
        "ssn-sosa-cco-extension.ttl"
    ),
}

EXPECTED_CURRENT_SOSA_SHA256 = {
    "integrated": (
        "c31997d7e7b8c5e0bffd3f23a4597ab4be80786978462fefe800c4c7a5dc0c11"
    ),
    "alignment_core": (
        "17695ef17379924449153b2c92ffaed6b57d497a1b2d1e854f584614cebec770"
    ),
    "strict_bfo_mapping": (
        "676b31620df10db5c26c46bcc44b2dfd5939d606b16e0fa8a910926e8497c3af"
    ),
    "bfo_projection": (
        "b5c1163eb6ab24c2e111e9e76c7b97acb20d897c9d1abc3daa555628206da5b0"
    ),
    "cco_extension": (
        "2908f89648d42dc928f7225056216f1cbf3bcdc79de1bcf770b40a017a5e9bf5"
    ),
}

PRODUCT_SPECS: dict[str, dict[str, Any]] = {
    "alignment_core": {
        "filename": "sosa-alignment-core.ttl",
        "maintained_path": (
            "releases/sosa-next/sosa-alignment-core.ttl"
        ),
        "ontology_iri": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/alignment-core"
        ),
        "release_iri_suffix": "sosa-next/alignment-core",
        "label": "SOSA-next Alignment Core",
        "description": (
            "Provides the import-free target-neutral module "
            "for the governed forthcoming SOSA mapping. "
            "No direct target-neutral mapping axiom is "
            "currently active."
        ),
        "imports": (),
        "prefixes": modular_products.PREFIXES,
        "categories": frozenset({"target_neutral"}),
        "axiom_count": 0,
        "logical_triple_count": 0,
        "total_triple_count": 8,
        "body_sha256": (
            "e3b0c44298fc1c149afbf4c8996fb924"
            "27ae41e4649b934ca495991b7852b855"
        ),
        "sha256": (
            "413018bbca9abc276102ddc97a3cfbf2"
            "803d170ef8c98f778869c2c89ae2425a"
        ),
    },
    "strict_bfo_mapping": {
        "filename": "sosa-bfo-mapping.ttl",
        "maintained_path": (
            "releases/sosa-next/sosa-bfo-mapping.ttl"
        ),
        "ontology_iri": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/bfo-mapping"
        ),
        "release_iri_suffix": "sosa-next/bfo-mapping",
        "label": "SOSA-next BFO Mapping",
        "description": (
            "Directly asserts the governed BFO-bearing "
            "axioms for the forthcoming SOSA mapping and "
            "imports the SOSA-next alignment core."
        ),
        "imports": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/alignment-core",
        ),
        "prefixes": modular_products.STRICT_BFO_PREFIXES,
        "categories": frozenset({"bfo_bearing"}),
        "axiom_count": 21,
        "logical_triple_count": 157,
        "total_triple_count": 166,
        "body_sha256": (
            "e8ebb11880e44fb2b4665b0741e838cf"
            "a300ad7cfd54faf14c930f80c22ee7da"
        ),
        "sha256": (
            "b4e5c485ecb176472384ed97dbaa83d3"
            "84c340340fa896d04ea54d9d2fc34e93"
        ),
    },
    "cco_extension": {
        "filename": "sosa-cco-extension.ttl",
        "maintained_path": (
            "releases/sosa-next/sosa-cco-extension.ttl"
        ),
        "ontology_iri": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/cco-extension"
        ),
        "release_iri_suffix": "sosa-next/cco-extension",
        "label": "SOSA-next CCO Extension",
        "description": (
            "Directly asserts the governed CCO-bearing and "
            "mixed BFO/CCO axioms for the forthcoming SOSA "
            "mapping and imports the SOSA-next BFO mapping."
        ),
        "imports": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/bfo-mapping",
        ),
        "prefixes": modular_products.CCO_EXTENSION_PREFIXES,
        "categories": frozenset(
            {
                "cco_bearing",
                "mixed_bfo_cco",
            }
        ),
        "axiom_count": 24,
        "logical_triple_count": 116,
        "total_triple_count": 125,
        "body_sha256": (
            "3b0d64f9036585febd548e5c404f31e"
            "8ec718bd12faf9fa6e4cc9d62c7f6fee4"
        ),
        "sha256": (
            "e65e96f15a55e19fc43be8dbda6e5635"
            "1ef40bbd6e0fa9368a240e83c5d6bb69"
        ),
    },
}

CATEGORY_TO_PRODUCT = {
    "target_neutral": "alignment_core",
    "bfo_bearing": "strict_bfo_mapping",
    "cco_bearing": "cco_extension",
    "mixed_bfo_cco": "cco_extension",
}

EXPECTED_WORKBOOK_COUNTS = {
    "governed_row_count": 119,
    "unique_row_id_count": 119,
    "active_mapping_count": 45,
    "deferred_mapping_count": 26,
    "explicitly_unmapped_row_count": 48,
    "canonical_authoritative_axiom_count": 45,
}

EXPECTED_CATEGORY_COUNTS = {
    "bfo_bearing": 21,
    "cco_bearing": 23,
    "mixed_bfo_cco": 1,
}


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_path(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def current_sosa_hashes() -> dict[str, str]:
    return {
        key: sha256_path(path)
        for key, path in CURRENT_SOSA_PRODUCTS.items()
    }


def validate_current_sosa_products() -> dict[str, str]:
    actual = current_sosa_hashes()

    if actual != EXPECTED_CURRENT_SOSA_SHA256:
        raise RuntimeError(
            "Current-SOSA maintained products changed.\n"
            f"Expected: {EXPECTED_CURRENT_SOSA_SHA256}\n"
            f"Actual:   {actual}"
        )

    return actual


def build_publication_metadata() -> Any:
    base = publication_metadata.load_metadata(
        METADATA_PATH
    )

    base_keys = {
        product.key
        for product in base.products
    }

    missing = set(PRODUCT_ORDER) - base_keys

    if missing:
        raise RuntimeError(
            "Publication metadata is missing product keys: "
            f"{sorted(missing)}"
        )

    updated = []

    for product in base.products:
        spec = PRODUCT_SPECS.get(product.key)

        if spec is None:
            updated.append(product)
            continue

        updated.append(
            replace(
                product,
                path=spec["maintained_path"],
                stable_ontology_iri=spec["ontology_iri"],
                release_iri_suffix=(
                    spec["release_iri_suffix"]
                ),
                label=spec["label"],
                description=spec["description"],
            )
        )

    publication = replace(
        base.publication,
        generated_warning=(
            "Generated from "
            "mappings/SOSA-next-to-BFO-COMS.xlsx; "
            "do not edit this ontology product directly."
        ),
    )

    return replace(
        base,
        publication=publication,
        products=tuple(updated),
    )


def classify_workbook_rows(
    rows: list[coms.WorkbookRow],
) -> tuple[
    list[coms.WorkbookRow],
    list[coms.WorkbookRow],
    list[coms.WorkbookRow],
]:
    active = [
        row
        for row in rows
        if (
            row.subject_text
            and row.predicate_text
            and row.target_text
        )
    ]

    deferred = [
        row
        for row in rows
        if (
            row.subject_text
            and not row.predicate_text
            and not row.target_text
            and row.reasoning_text
        )
    ]

    explicitly_unmapped = [
        row
        for row in rows
        if (
            row.subject_text
            and not row.predicate_text
            and not row.target_text
            and not row.reasoning_text
        )
    ]

    malformed = [
        row
        for row in rows
        if (
            row not in active
            and row not in deferred
            and row not in explicitly_unmapped
        )
    ]

    if malformed:
        rendered = "\n".join(
            (
                f"{row.diagnostic_id}: "
                f"subject={row.subject_text!r}; "
                f"predicate={row.predicate_text!r}; "
                f"target={row.target_text!r}"
            )
            for row in malformed
        )

        raise RuntimeError(
            "Malformed SOSA-next workbook rows:\n"
            + rendered
        )

    return active, deferred, explicitly_unmapped


def process_active_rows(
    output_dir: Path,
) -> tuple[
    list[coms.ProcessedRow],
    dict[str, int],
    Graph,
]:
    source_hashes = (
        mapping_checker.validate_source_pins()
    )

    merged_source_path = (
        output_dir / "sosa-next-source-merged.ttl"
    )

    source_graph = (
        mapping_checker.build_merged_source(
            merged_source_path
        )
    )

    rows, workbook_stats = coms.read_workbook(
        WORKBOOK
    )

    coms.validate_workbook_row_ids(
        rows,
        workbook_stats,
    )

    active, deferred, explicitly_unmapped = (
        classify_workbook_rows(rows)
    )

    counts = {
        "governed_row_count": len(rows),
        "unique_row_id_count": (
            workbook_stats.unique_row_id_count
        ),
        "active_mapping_count": len(active),
        "deferred_mapping_count": len(deferred),
        "explicitly_unmapped_row_count": len(
            explicitly_unmapped
        ),
    }

    for key, expected in (
        EXPECTED_WORKBOOK_COUNTS.items()
    ):
        if key == "canonical_authoritative_axiom_count":
            continue

        actual = counts[key]

        if actual != expected:
            raise RuntimeError(
                f"{key}: expected {expected}; "
                f"found {actual}"
            )

    previous_prefix_files = dict(
        coms.PREFIX_FILES
    )
    previous_source_imports = tuple(
        coms.SOURCE_IMPORTS
    )

    stats = coms.WorkbookStats(
        worksheets_read=list(
            workbook_stats.worksheets_read
        )
    )

    mapping_checker.configure_coms_resolver(
        merged_source_path
    )

    try:
        processed = coms.validate_and_process_rows(
            active,
            coms.Resolver(),
            stats,
        )
    finally:
        coms.PREFIX_FILES = previous_prefix_files
        coms.SOURCE_IMPORTS = previous_source_imports

    if dict(coms.PREFIX_FILES) != previous_prefix_files:
        raise RuntimeError(
            "PREFIX_FILES was not restored."
        )

    if tuple(coms.SOURCE_IMPORTS) != (
        previous_source_imports
    ):
        raise RuntimeError(
            "SOURCE_IMPORTS was not restored."
        )

    if len(processed) != 45:
        raise RuntimeError(
            f"Expected 45 processed mappings; "
            f"found {len(processed)}"
        )

    counts["source_triple_count"] = len(source_graph)
    counts["source_file_count"] = len(source_hashes)

    return processed, counts, source_graph


def build_product_records(
    processed: list[coms.ProcessedRow],
) -> tuple[
    dict[str, list[dict[str, Any]]],
    dict[str, int],
]:
    records = {
        key: []
        for key in PRODUCT_ORDER
    }

    category_counts: Counter[str] = Counter()
    row_ids: set[str] = set()
    axiom_ids: set[str] = set()

    for item in processed:
        audit = item.identity_audit

        if audit is None:
            raise RuntimeError(
                f"{item.row.diagnostic_id}: "
                "missing canonical identity audit"
            )

        if len(audit.authoritative_axioms) != 1:
            raise RuntimeError(
                f"{item.row.diagnostic_id}: expected "
                "one authoritative axiom"
            )

        identity = audit.authoritative_axioms[0]
        canonical = (
            coms.canonical_input_for_processed_row(
                item
            )
        )

        axiom_input = (
            axiom_input_from_canonical_row(
                identity,
                canonical,
            )
        )

        category = classify_target_category(
            axiom_input
        )

        try:
            product_key = CATEGORY_TO_PRODUCT[
                category
            ]
        except KeyError as exc:
            raise RuntimeError(
                f"Unsupported target category: "
                f"{category}"
            ) from exc

        row_id = item.row.stable_row_id
        axiom_id = f"sha256:{identity.sha256}"

        if row_id in row_ids:
            raise RuntimeError(
                f"Duplicate active RowID: {row_id}"
            )

        if axiom_id in axiom_ids:
            raise RuntimeError(
                "Duplicate authoritative axiom ID: "
                f"{axiom_id}"
            )

        row_ids.add(row_id)
        axiom_ids.add(axiom_id)
        category_counts[category] += 1

        records[product_key].append(
            {
                "row_id": row_id,
                "subject": item.row.subject_text,
                "category": category,
                "axiom_id": axiom_id,
                "rendered_lines": tuple(
                    modular_products
                    .render_authoritative_axiom_lines(
                        canonical,
                        axiom_id,
                    )
                ),
            }
        )

    actual_categories = dict(category_counts)

    if actual_categories != EXPECTED_CATEGORY_COUNTS:
        raise RuntimeError(
            "Unexpected SOSA-next category partition.\n"
            f"Expected: {EXPECTED_CATEGORY_COUNTS}\n"
            f"Actual:   {actual_categories}"
        )

    if len(row_ids) != 45 or len(axiom_ids) != 45:
        raise RuntimeError(
            "Expected 45 unique active RowIDs and "
            "45 unique authoritative axiom IDs."
        )

    return records, actual_categories


def body_bytes(
    records: list[dict[str, Any]],
) -> bytes:
    blocks = [
        "\n".join(record["rendered_lines"])
        for record in sorted(
            records,
            key=lambda value: value["axiom_id"],
        )
    ]

    if not blocks:
        return b""

    return (
        "\n\n".join(blocks).rstrip() + "\n"
    ).encode("utf-8")


def logical_graph(
    graph: Graph,
    ontology_iri: str,
) -> Graph:
    ontology = URIRef(ontology_iri)
    result = Graph()

    for triple in graph:
        if triple[0] != ontology:
            result.add(triple)

    return result


def serialize_product(
    metadata: Any,
    product_key: str,
    records: list[dict[str, Any]],
) -> tuple[bytes, Graph, dict[str, Any]]:
    spec = PRODUCT_SPECS[product_key]

    observed_categories = {
        record["category"]
        for record in records
    }

    if not observed_categories <= spec["categories"]:
        raise RuntimeError(
            f"{product_key}: prohibited categories "
            f"{sorted(observed_categories - spec['categories'])}"
        )

    if len(records) != spec["axiom_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['axiom_count']} axioms; "
            f"found {len(records)}"
        )

    body = body_bytes(records)
    body_hash = sha256_bytes(body)

    if body_hash != spec["body_sha256"]:
        raise RuntimeError(
            f"{product_key}: axiom-body hash mismatch\n"
            f"Expected: {spec['body_sha256']}\n"
            f"Actual:   {body_hash}"
        )

    header = (
        publication_metadata
        .render_ontology_header_bytes(
            metadata,
            product_key,
            spec["imports"],
            generated_notice=GENERATED_NOTICE,
            prefixes=spec["prefixes"],
        )
    )

    serialized = (
        header
        if not body
        else header + b"\n" + body
    )

    issues = (
        publication_metadata
        .validate_serialized_ontology_header(
            serialized,
            metadata,
            product_key,
            spec["imports"],
            generated_notice=GENERATED_NOTICE,
            prefixes=spec["prefixes"],
        )
    )

    if issues:
        rendered = "\n".join(
            (
                f"{issue.code}: {issue.field}: "
                f"{issue.message}"
            )
            for issue in issues
        )

        raise RuntimeError(
            f"{product_key}: metadata validation "
            f"failed:\n{rendered}"
        )

    graph = Graph()
    graph.parse(
        data=serialized.decode("utf-8"),
        format="turtle",
    )

    ontology = URIRef(spec["ontology_iri"])

    declarations = set(
        graph.triples(
            (None, RDF.type, OWL.Ontology)
        )
    )

    if declarations != {
        (ontology, RDF.type, OWL.Ontology)
    }:
        raise RuntimeError(
            f"{product_key}: ontology declaration "
            "mismatch"
        )

    imports = {
        str(value)
        for value in graph.objects(
            ontology,
            OWL.imports,
        )
    }

    if imports != set(spec["imports"]):
        raise RuntimeError(
            f"{product_key}: import mismatch"
        )

    if any(
        True
        for _ in graph.triples(
            (None, OWL.versionIRI, None)
        )
    ):
        raise RuntimeError(
            f"{product_key}: development product "
            "contains owl:versionIRI"
        )

    logical = logical_graph(
        graph,
        spec["ontology_iri"],
    )

    if len(logical) != spec["logical_triple_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['logical_triple_count']} "
            f"logical triples; found {len(logical)}"
        )

    if len(graph) != spec["total_triple_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['total_triple_count']} "
            f"total triples; found {len(graph)}"
        )

    product_hash = sha256_bytes(serialized)

    if product_hash != spec["sha256"]:
        raise RuntimeError(
            f"{product_key}: complete product hash "
            "mismatch\n"
            f"Expected: {spec['sha256']}\n"
            f"Actual:   {product_hash}"
        )

    result = {
        "maintained_path": spec["maintained_path"],
        "ontology_iri": spec["ontology_iri"],
        "imports": list(spec["imports"]),
        "axiom_count": len(records),
        "row_count": len(
            {
                record["row_id"]
                for record in records
            }
        ),
        "categories": sorted(
            observed_categories
        ),
        "logical_triple_count": len(logical),
        "total_triple_count": len(graph),
        "body_sha256": body_hash,
        "sha256": product_hash,
        "byte_size": len(serialized),
        "subjects": sorted(
            record["subject"]
            for record in records
        ),
        "row_ids": sorted(
            record["row_id"]
            for record in records
        ),
        "axiom_ids": sorted(
            record["axiom_id"]
            for record in records
        ),
    }

    return serialized, logical, result


def build_candidate(
    output_dir: Path,
    *,
    reverse_input: bool = False,
) -> dict[str, Any]:
    output_dir = output_dir.resolve()
    shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    validate_current_sosa_products()

    metadata = build_publication_metadata()

    processed, counts, _ = process_active_rows(
        output_dir
    )

    records, categories = build_product_records(
        processed
    )

    products: dict[str, dict[str, Any]] = {}
    logical_graphs: dict[str, Graph] = {}
    product_paths: dict[str, Path] = {}

    for product_key in PRODUCT_ORDER:
        supplied = records[product_key]

        if reverse_input:
            supplied = list(reversed(supplied))

        serialized, logical, result = (
            serialize_product(
                metadata,
                product_key,
                supplied,
            )
        )

        path = (
            output_dir
            / PRODUCT_SPECS[product_key]["filename"]
        )

        path.write_bytes(serialized)

        product_paths[product_key] = path
        logical_graphs[product_key] = logical
        products[product_key] = {
            **result,
            "candidate_path": str(path),
        }

    combined = Graph()

    for graph in logical_graphs.values():
        for triple in graph:
            combined.add(triple)

    summed = sum(
        len(graph)
        for graph in logical_graphs.values()
    )

    if summed != 273 or len(combined) != 273:
        raise RuntimeError(
            "Expected 273 modular logical triples; "
            f"sum={summed}, distinct={len(combined)}"
        )

    reference_path = (
        output_dir / "active-mappings-reference.ttl"
    )

    reference = (
        mapping_checker.render_active_ontology(
            processed,
            reference_path,
        )
    )

    reference_logical = logical_graph(
        reference,
        str(mapping_checker.ONTOLOGY_IRI),
    )

    if len(reference_logical) != 273:
        raise RuntimeError(
            "Expected 273 integrated logical triples; "
            f"found {len(reference_logical)}"
        )

    if not isomorphic(
        combined,
        reference_logical,
    ):
        raise RuntimeError(
            "The modular product union differs from "
            "the integrated active mapping graph."
        )

    summary = {
        **counts,
        "canonical_authoritative_axiom_count": 45,
        "category_counts": categories,
        "combined_logical_triple_count": len(
            combined
        ),
        "integrated_reference_logical_triple_count": (
            len(reference_logical)
        ),
        "logical_union_isomorphic": True,
        "resolver_state_restored": True,
        "current_sosa_products_unchanged": True,
        "products": products,
        "product_paths": {
            key: str(path)
            for key, path in product_paths.items()
        },
    }

    (output_dir / "candidate-summary.json").write_text(
        json.dumps(
            summary,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    return summary


def compare_candidate_builds(
    first: Mapping[str, Any],
    second: Mapping[str, Any],
) -> None:
    for product_key in PRODUCT_ORDER:
        first_path = Path(
            first["product_paths"][product_key]
        )
        second_path = Path(
            second["product_paths"][product_key]
        )

        if first_path.read_bytes() != (
            second_path.read_bytes()
        ):
            raise RuntimeError(
                f"{product_key}: independent "
                "candidate builds differ"
            )


def build_reasoning_closure(
    serialized_products: tuple[bytes, ...],
    *,
    include_target_dependency: bool,
) -> Graph:
    dependencies = [
        *mapping_checker.SOURCE_FILES,
    ]

    if include_target_dependency:
        dependencies.insert(
            0,
            REPO_ROOT / "imports/cco.ttl",
        )

    return (
        modular_products
        .build_fixed_validation_closure(
            serialized_products,
            dependencies,
        )
    )


def reason_products(
    candidate: Mapping[str, Any],
    output_dir: Path,
    robot_path: str | None,
) -> dict[str, Any]:
    robot = mapping_checker.resolve_robot(
        robot_path
    )

    paths = {
        key: Path(
            candidate["product_paths"][key]
        )
        for key in PRODUCT_ORDER
    }

    serialized = {
        key: path.read_bytes()
        for key, path in paths.items()
    }

    profiles = {
        "alignment_core": build_reasoning_closure(
            (
                serialized["alignment_core"],
            ),
            include_target_dependency=False,
        ),
        "strict_bfo_mapping": build_reasoning_closure(
            (
                serialized["strict_bfo_mapping"],
                serialized["alignment_core"],
            ),
            include_target_dependency=True,
        ),
        "cco_extension": build_reasoning_closure(
            (
                serialized["cco_extension"],
                serialized["strict_bfo_mapping"],
                serialized["alignment_core"],
            ),
            include_target_dependency=True,
        ),
    }

    reasoning_root = output_dir / "reasoning"
    reasoning_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    results: dict[str, Any] = {}

    for product_key in PRODUCT_ORDER:
        closure = profiles[product_key]

        if any(
            True
            for _ in closure.triples(
                (None, OWL.imports, None)
            )
        ):
            raise RuntimeError(
                f"{product_key}: fixed validation "
                "closure retains owl:imports"
            )

        closure_path = (
            reasoning_root
            / f"{product_key}-closure.ttl"
        )
        reasoned_path = (
            reasoning_root
            / f"{product_key}-reasoned.ttl"
        )
        unsat_path = (
            reasoning_root
            / f"{product_key}-unsatisfiable.ttl"
        )

        closure.serialize(
            closure_path,
            format="turtle",
        )

        result = mapping_checker.run_reasoner(
            robot,
            closure_path,
            reasoned_path,
            unsat_path,
        )

        if not result["passed"]:
            raise RuntimeError(
                f"{product_key}: HermiT validation "
                f"failed: {result}"
            )

        if result["unsatisfiable_classes"]:
            raise RuntimeError(
                f"{product_key}: unexpected "
                "unsatisfiable classes: "
                f"{result['unsatisfiable_classes']}"
            )

        results[product_key] = {
            **result,
            "closure_triple_count": len(closure),
            "closure_path": str(closure_path),
        }

    return results


def run_transaction(
    output_dir: Path,
    robot_path: str | None = None,
) -> dict[str, Any]:
    output_dir = output_dir.resolve()
    shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    before = validate_current_sosa_products()

    first = build_candidate(
        output_dir / "build-a",
    )

    second = build_candidate(
        output_dir / "build-b",
        reverse_input=True,
    )

    compare_candidate_builds(first, second)

    reasoning = reason_products(
        first,
        output_dir,
        robot_path,
    )

    after = validate_current_sosa_products()

    if before != after:
        raise RuntimeError(
            "A current-SOSA maintained product "
            "changed during generation."
        )

    summary = {
        **first,
        "independent_builds_byte_identical": True,
        "reasoning": reasoning,
        "current_sosa_products_unchanged": True,
    }

    (output_dir / "transaction-summary.json").write_text(
        json.dumps(
            summary,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    return summary


def maintained_products_are_fresh(
    candidate: Mapping[str, Any],
) -> bool:
    for product_key in PRODUCT_ORDER:
        destination = MAINTAINED_PRODUCTS[
            product_key
        ]

        if not destination.is_file():
            return False

        candidate_path = Path(
            candidate["product_paths"][
                product_key
            ]
        )

        if (
            destination.read_bytes()
            != candidate_path.read_bytes()
        ):
            return False

    return True


def replace_outputs_atomically(
    candidate_paths: Mapping[str, Path],
    destinations: Mapping[str, Path],
    *,
    transaction_dir: Path,
    post_replace: Callable[[], None] | None = None,
) -> None:
    backup_dir = transaction_dir / "backups"
    staging_dir = transaction_dir / "staging"

    backup_dir.mkdir(
        parents=True,
        exist_ok=True,
    )
    staging_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    backups: dict[str, Path] = {}
    originally_missing: set[str] = set()
    staged: dict[str, Path] = {}

    for product_key in PRODUCT_ORDER:
        destination = destinations[product_key]

        if destination.exists():
            backup = backup_dir / product_key
            shutil.copy2(destination, backup)
            backups[product_key] = backup
        else:
            originally_missing.add(product_key)

        stage = staging_dir / product_key
        shutil.copy2(
            candidate_paths[product_key],
            stage,
        )
        staged[product_key] = stage

    try:
        for product_key in PRODUCT_ORDER:
            destination = destinations[product_key]
            destination.parent.mkdir(
                parents=True,
                exist_ok=True,
            )

            os.replace(
                staged[product_key],
                destination,
            )

        if post_replace is not None:
            post_replace()
    except Exception:
        for product_key in PRODUCT_ORDER:
            destination = destinations[product_key]

            if product_key in backups:
                destination.parent.mkdir(
                    parents=True,
                    exist_ok=True,
                )
                shutil.copy2(
                    backups[product_key],
                    destination,
                )
            elif (
                product_key in originally_missing
                and destination.exists()
            ):
                destination.unlink()

        raise


def write_maintained_products(
    robot_path: str | None = None,
) -> dict[str, Any]:
    build_root = REPO_ROOT / "build"
    build_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    with tempfile.TemporaryDirectory(
        prefix=".sosa-next-products-",
        dir=build_root,
    ) as temporary:
        transaction_dir = Path(temporary)

        summary = run_transaction(
            transaction_dir,
            robot_path,
        )

        candidate_paths = {
            key: Path(
                summary["product_paths"][key]
            )
            for key in PRODUCT_ORDER
        }

        replace_outputs_atomically(
            candidate_paths,
            MAINTAINED_PRODUCTS,
            transaction_dir=transaction_dir,
        )

        if not maintained_products_are_fresh(
            summary
        ):
            raise RuntimeError(
                "Maintained SOSA-next products differ "
                "from the validated candidate build."
            )

        summary["maintained_write"] = True

        return summary


def check_maintained_products(
    output_dir: Path,
    robot_path: str | None = None,
) -> dict[str, Any]:
    summary = run_transaction(
        output_dir,
        robot_path,
    )

    fresh = maintained_products_are_fresh(
        summary
    )

    result = {
        **summary,
        "maintained_products_fresh": fresh,
        "passed": fresh,
    }

    (output_dir / "check-summary.json").write_text(
        json.dumps(
            result,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    return result


def print_summary(summary: Mapping[str, Any]) -> None:
    print(
        "Governed rows: "
        f"{summary['governed_row_count']}"
    )
    print(
        "Active mappings: "
        f"{summary['active_mapping_count']}"
    )
    print(
        "Deferred mappings: "
        f"{summary['deferred_mapping_count']}"
    )
    print(
        "Explicitly unmapped rows: "
        f"{summary['explicitly_unmapped_row_count']}"
    )
    print(
        "Canonical authoritative axioms: "
        f"{summary['canonical_authoritative_axiom_count']}"
    )
    print(
        "Target categories: "
        f"{summary['category_counts']}"
    )
    print(
        "Combined logical triples: "
        f"{summary['combined_logical_triple_count']}"
    )

    for product_key in PRODUCT_ORDER:
        product = summary["products"][
            product_key
        ]
        reasoning = summary["reasoning"][
            product_key
        ]

        print(f"{product_key}:")
        print(
            f"  axioms: "
            f"{product['axiom_count']}"
        )
        print(
            f"  logical triples: "
            f"{product['logical_triple_count']}"
        )
        print(
            f"  total triples: "
            f"{product['total_triple_count']}"
        )
        print(
            f"  SHA-256: "
            f"{product['sha256']}"
        )
        print(
            "  reasoning closure triples: "
            f"{reasoning['closure_triple_count']}"
        )
        print(
            "  unsatisfiable classes: "
            f"{len(reasoning['unsatisfiable_classes'])}"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__
    )

    parser.add_argument(
        "--output-dir",
        default=(
            "/tmp/sosa-next-product-generation"
        ),
        help=(
            "Directory for candidate and validation "
            "evidence."
        ),
    )

    parser.add_argument(
        "--robot",
        help="Optional explicit ROBOT executable path.",
    )

    parser.add_argument(
        "--write-maintained",
        action="store_true",
        help=(
            "Atomically replace the three maintained "
            "SOSA-next products after all gates pass."
        ),
    )

    args = parser.parse_args(argv)

    try:
        if args.write_maintained:
            summary = write_maintained_products(
                args.robot
            )
        else:
            summary = run_transaction(
                Path(args.output_dir),
                args.robot,
            )
    except Exception as exc:
        print(
            "SOSA-next product generation: FAIL"
        )
        print(exc)
        return 1

    print_summary(summary)

    if args.write_maintained:
        print(
            "Maintained SOSA-next products: UPDATED"
        )
    else:
        print(
            "Candidate SOSA-next products: PASS"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
