#!/usr/bin/env python3
"""Generate and validate the maintained SOSA-next modular products."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import tempfile
from collections import Counter
from dataclasses import replace
from pathlib import Path
from typing import Any, Callable, Mapping

from rdflib import Graph, URIRef
from rdflib.compare import isomorphic
from rdflib.namespace import OWL, RDF

import check_sosa_next_mapping as mapping_checker
import sosa_2023_mapping_status as mapping_status
import generate_mapping_from_coms as coms
import generate_sosa_2023_ro_mapping as ro_generator
import modular_products
import publication_metadata
from release_context import (
    FormalReleaseContext,
    validate_formal_release_context,
)
from product_dispositions import (
    axiom_input_from_canonical_row,
    classify_target_category,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = REPO_ROOT / "mappings/SOSA-next-to-BFO-COMS.xlsx"
METADATA_PATH = REPO_ROOT / "config/publication-metadata.toml"

SOSA_2023_PUBLICATION_METADATA_PATH = (
    REPO_ROOT
    / "config/sosa-2023-publication-metadata.toml"
)

FORMAL_GENERATED_NOTICE = (
    "# Generated from the governed SOSA 2023 COMS mapping and "
    "publication metadata. Do not edit this ontology directly."
)

FORMAL_INTEGRATED_EXTERNAL_IMPORTS = (
    "http://www.w3.org/ns/sosa/",
    "http://www.w3.org/ns/sosa/systems/",
    "http://www.w3.org/ns/sosa/sampling/",
    (
        "https://www.commoncoreontologies.org/"
        "CommonCoreOntologiesMerged"
    ),
)

GENERATED_NOTICE = (
    "# Generated from mappings/SOSA-next-to-BFO-COMS.xlsx. "
    "Do not edit this file directly."
)

PRODUCT_ORDER = (
    "integrated",
    "strict_bfo_mapping",
    "cco_extension",
)

DEVELOPMENT_PRODUCT_ORDER = (
    *PRODUCT_ORDER,
    "ro_mapping",
)

MODULAR_PRODUCT_ORDER = (
    "strict_bfo_mapping",
    "cco_extension",
)

MAINTAINED_PRODUCTS = {
    "integrated": (
        REPO_ROOT
        / "releases/sosa-next/sosa-integrated.ttl"
    ),
    "strict_bfo_mapping": (
        REPO_ROOT
        / "releases/sosa-next/sosa-bfo-mapping.ttl"
    ),
    "cco_extension": (
        REPO_ROOT
        / "releases/sosa-next/sosa-cco-extension.ttl"
    ),
    "ro_mapping": (
        REPO_ROOT
        / "releases/sosa-next/sosa-ro-mapping.ttl"
    ),
}

RETIRED_MAINTAINED_PRODUCTS = (
    REPO_ROOT
    / "releases/sosa-next/sosa-alignment-core.ttl",
)

CURRENT_SOSA_PRODUCTS = {
    "integrated": REPO_ROOT / "SSN2BFO.ttl",
    "alignment_core": (
        REPO_ROOT
        / "releases/current-ssn-sosa/"
        "ssn-sosa-alignment-core.ttl"
    ),
    "strict_bfo_mapping": (
        REPO_ROOT
        / "releases/current-ssn-sosa/"
        "ssn-sosa-bfo-mapping.ttl"
    ),
    "cco_extension": (
        REPO_ROOT
        / "releases/current-ssn-sosa/"
        "ssn-sosa-cco-extension.ttl"
    ),
}

EXPECTED_CURRENT_SOSA_SHA256 = {
    "integrated": (
        "c31997d7e7b8c5e0bffd3f23a4597ab4be80786978462fefe800c4c7a5dc0c11"
    ),
    "alignment_core": (
        "17695ef17379924449153b2c92ffaed6b57d497a1b2d1e854f584614cebec770"
    ),
    "strict_bfo_mapping": (
        "676b31620df10db5c26c46bcc44b2dfd5939d606b16e0fa8a910926e8497c3af"
    ),
    "cco_extension": (
        "2908f89648d42dc928f7225056216f1cbf3bcdc79de1bcf770b40a017a5e9bf5"
    ),
}

PRODUCT_SPECS: dict[str, dict[str, Any]] = {
    "integrated": {
        "filename": "sosa-integrated.ttl",
        "maintained_path": (
            "releases/sosa-next/sosa-integrated.ttl"
        ),
        "ontology_iri": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/integrated"
        ),
        "release_iri_suffix": "sosa-next/integrated",
        "label": "SOSA-next Integrated Mapping",
        "description": (
            "Directly asserts the complete governed axiom set "
            "for the forthcoming SOSA mapping and imports the "
            "governed SOSA, BFO, and CCO dependencies required "
            "for the complete consumer entry point."
        ),
        "imports": (
            "http://www.w3.org/ns/sosa/",
            "http://www.w3.org/ns/sosa/systems/",
            "http://www.w3.org/ns/sosa/sampling/",
            (
                "http://www.sks.ai/SSN2BFO/"
                "development/sosa-next/"
                "source-declaration-overlay"
            ),
            (
                "https://www.commoncoreontologies.org/"
                "CommonCoreOntologiesMerged"
            ),
        ),
        "prefixes": (
            ("cco", "https://www.commoncoreontologies.org/"),
            ("bfo", "http://purl.obolibrary.org/obo/"),
            ("adms", "http://www.w3.org/ns/adms#"),
            ("dcterms", "http://purl.org/dc/terms/"),
            ("owl", "http://www.w3.org/2002/07/owl#"),
            ("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
            ("rdfs", "http://www.w3.org/2000/01/rdf-schema#"),
            ("sampling", "http://www.w3.org/ns/sosa/sampling/"),
            ("sosa", "http://www.w3.org/ns/sosa/"),
            ("ssn", "http://www.w3.org/ns/ssn/"),
            ("ssn-system", "http://www.w3.org/ns/ssn/systems/"),
        ),
        "categories": frozenset(
            {
                "bfo_bearing",
                "cco_bearing",
                "mixed_bfo_cco",
            }
        ),
        "axiom_count": 55,
        "logical_triple_count": 277,
        "total_triple_count": 290,
        "body_sha256": (
            '61738c961589fb553c551a33e7bee2050a1b5485389dcb9136aa6e17dab6fb13'
        ),
        "sha256": (
            '3f502821476478252cdd9feb316b47612daa473e511597970a1351617d5cfc12'
        ),
    },
    "strict_bfo_mapping": {
        "filename": "sosa-bfo-mapping.ttl",
        "maintained_path": (
            "releases/sosa-next/sosa-bfo-mapping.ttl"
        ),
        "ontology_iri": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/bfo-mapping"
        ),
        "release_iri_suffix": "sosa-next/bfo-mapping",
        "label": "SOSA-next BFO Mapping",
        "description": (
            "Directly asserts the governed BFO-bearing axioms "
            "for the forthcoming SOSA mapping without importing "
            "another project product."
        ),
        "imports": (),
        "prefixes": (
            ("bfo", "http://purl.obolibrary.org/obo/"),
            ("adms", "http://www.w3.org/ns/adms#"),
            ("dcterms", "http://purl.org/dc/terms/"),
            ("owl", "http://www.w3.org/2002/07/owl#"),
            ("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
            ("rdfs", "http://www.w3.org/2000/01/rdf-schema#"),
            ("sampling", "http://www.w3.org/ns/sosa/sampling/"),
            ("sosa", "http://www.w3.org/ns/sosa/"),
            ("ssn", "http://www.w3.org/ns/ssn/"),
            ("ssn-system", "http://www.w3.org/ns/ssn/systems/"),
        ),
        "categories": frozenset({"bfo_bearing"}),
        "axiom_count": 24,
        "logical_triple_count": 154,
        "total_triple_count": 162,
        "body_sha256": (
            '5d229ec03094212fdfb3078e1dd993f1b8a63d688c669aa7fd2c732ead295954'
        ),
        "sha256": (
            '1ae415bc96940e4007d064102f556aa544593616a0eff984534406028b846efb'
        ),
    },
    "cco_extension": {
        "filename": "sosa-cco-extension.ttl",
        "maintained_path": (
            "releases/sosa-next/sosa-cco-extension.ttl"
        ),
        "ontology_iri": (
            "http://www.sks.ai/SSN2BFO/"
            "development/sosa-next/cco-extension"
        ),
        "release_iri_suffix": "sosa-next/cco-extension",
        "label": "SOSA-next CCO Extension",
        "description": (
            "Directly asserts the governed CCO-bearing and mixed "
            "BFO/CCO axioms for the forthcoming SOSA mapping and "
            "imports the SOSA-next BFO mapping."
        ),
        "imports": (
            (
                "http://www.sks.ai/SSN2BFO/"
                "development/sosa-next/bfo-mapping"
            ),
        ),
        "prefixes": (
            ("cco", "https://www.commoncoreontologies.org/"),
            ("bfo", "http://purl.obolibrary.org/obo/"),
            ("adms", "http://www.w3.org/ns/adms#"),
            ("dcterms", "http://purl.org/dc/terms/"),
            ("owl", "http://www.w3.org/2002/07/owl#"),
            ("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
            ("rdfs", "http://www.w3.org/2000/01/rdf-schema#"),
            ("sampling", "http://www.w3.org/ns/sosa/sampling/"),
            ("sosa", "http://www.w3.org/ns/sosa/"),
            ("ssn", "http://www.w3.org/ns/ssn/"),
            ("ssn-system", "http://www.w3.org/ns/ssn/systems/"),
        ),
        "categories": frozenset(
            {
                "cco_bearing",
                "mixed_bfo_cco",
            }
        ),
        "axiom_count": 31,
        "logical_triple_count": 123,
        "total_triple_count": 132,
        "body_sha256": (
            '600677e891b41c17557c457c2c582826a3cb2287d3ff6d4c35d8d4d734eec758'
        ),
        "sha256": (
            '53a7cc6c0f664e51bf9f7ac28e3d067fc4fdcc750e22a34fe5c12c766e51dc19'
        ),
    },
}

CATEGORY_TO_PRODUCT = {
    "bfo_bearing": "strict_bfo_mapping",
    "cco_bearing": "cco_extension",
    "mixed_bfo_cco": "cco_extension",
}

EXPECTED_WORKBOOK_COUNTS = {
    "governed_row_count": 119,
    "unique_row_id_count": 119,
    "active_mapping_count": 55,
    "deferred_mapping_count": 0,
    "explicitly_unmapped_row_count": 64,
    "canonical_authoritative_axiom_count": 55,
}

EXPECTED_MAPPING_STATUS_COUNTS = {
    "no_direct_mapping_row_count": 64,
    "unreviewed_row_count": 0,
}

EXPECTED_CATEGORY_COUNTS = {
    "bfo_bearing": 24,
    "cco_bearing": 30,
    "mixed_bfo_cco": 1,
}


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_path(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def current_sosa_hashes() -> dict[str, str]:
    return {
        key: sha256_path(path)
        for key, path in CURRENT_SOSA_PRODUCTS.items()
    }


def validate_current_sosa_products() -> dict[str, str]:
    actual = current_sosa_hashes()

    if actual != EXPECTED_CURRENT_SOSA_SHA256:
        raise RuntimeError(
            "Current-SOSA maintained products changed.\n"
            f"Expected: {EXPECTED_CURRENT_SOSA_SHA256}\n"
            f"Actual:   {actual}"
        )

    return actual


def build_publication_metadata() -> Any:
    base = publication_metadata.load_metadata(
        METADATA_PATH
    )

    base_keys = {
        product.key
        for product in base.products
    }

    missing = set(PRODUCT_ORDER) - base_keys

    if missing:
        raise RuntimeError(
            "Publication metadata is missing product keys: "
            f"{sorted(missing)}"
        )

    updated = []

    for product in base.products:
        spec = PRODUCT_SPECS.get(product.key)

        if spec is None:
            updated.append(product)
            continue

        updated.append(
            replace(
                product,
                path=spec["maintained_path"],
                stable_ontology_iri=spec["ontology_iri"],
                release_iri_suffix=(
                    spec["release_iri_suffix"]
                ),
                label=spec["label"],
                description=spec["description"],
            )
        )

    publication = replace(
        base.publication,
        generated_warning=(
            "Generated from "
            "mappings/SOSA-next-to-BFO-COMS.xlsx; "
            "do not edit this ontology product directly."
        ),
    )

    return replace(
        base,
        publication=publication,
        products=tuple(updated),
    )


def classify_workbook_rows(
    rows: list[coms.WorkbookRow],
) -> tuple[
    list[coms.WorkbookRow],
    list[coms.WorkbookRow],
    list[coms.WorkbookRow],
]:
    """Legacy three-bucket compatibility view over MappingStatus."""

    classification = (
        mapping_status.classify_workbook_rows(
            rows
        )
    )

    explicitly_unmapped = [
        row
        for row in rows
        if row.mapping_status_text
        in {
            mapping_status.NO_DIRECT_MAPPING,
            mapping_status.UNREVIEWED,
        }
    ]

    return (
        list(classification.active),
        list(classification.deferred),
        explicitly_unmapped,
    )


def process_active_rows(
    output_dir: Path,
) -> tuple[
    list[coms.ProcessedRow],
    dict[str, int],
    Graph,
]:
    source_hashes = (
        mapping_checker.validate_source_pins()
    )
    mapping_checker.validate_target_cco_pin()

    merged_source_path = (
        output_dir / "sosa-next-source-merged.ttl"
    )

    source_graph = (
        mapping_checker.build_merged_source(
            merged_source_path
        )
    )

    rows, workbook_stats = coms.read_workbook(
        WORKBOOK
    )

    coms.validate_workbook_row_ids(
        rows,
        workbook_stats,
    )

    classification = (
        mapping_status.classify_workbook_rows(
            rows
        )
    )

    active = list(
        classification.active
    )
    deferred = list(
        classification.deferred
    )
    no_direct_mapping = list(
        classification.no_direct_mapping
    )
    unreviewed = list(
        classification.unreviewed
    )

    explicitly_unmapped = [
        row
        for row in rows
        if row.mapping_status_text
        in {
            mapping_status.NO_DIRECT_MAPPING,
            mapping_status.UNREVIEWED,
        }
    ]

    counts = {
        "governed_row_count": len(rows),
        "unique_row_id_count": (
            workbook_stats.unique_row_id_count
        ),
        "active_mapping_count": len(active),
        "deferred_mapping_count": len(deferred),
        "no_direct_mapping_row_count": len(
            no_direct_mapping
        ),
        "unreviewed_row_count": len(unreviewed),
        "explicitly_unmapped_row_count": len(
            explicitly_unmapped
        ),
    }

    for key, expected in (
        EXPECTED_WORKBOOK_COUNTS.items()
    ):
        if key == "canonical_authoritative_axiom_count":
            continue

        actual = counts[key]

        if actual != expected:
            raise RuntimeError(
                f"{key}: expected {expected}; "
                f"found {actual}"
            )

    for key, expected in (
        EXPECTED_MAPPING_STATUS_COUNTS.items()
    ):
        actual = counts[key]

        if actual != expected:
            raise RuntimeError(
                f"{key}: expected {expected}; "
                f"found {actual}"
            )

    previous_prefix_files = dict(
        coms.PREFIX_FILES
    )
    previous_source_imports = tuple(
        coms.SOURCE_IMPORTS
    )

    stats = coms.WorkbookStats(
        worksheets_read=list(
            workbook_stats.worksheets_read
        )
    )

    mapping_checker.configure_coms_resolver(
        merged_source_path
    )

    try:
        processed = coms.validate_and_process_rows(
            active,
            coms.Resolver(),
            stats,
        )
    finally:
        coms.PREFIX_FILES = previous_prefix_files
        coms.SOURCE_IMPORTS = previous_source_imports

    if dict(coms.PREFIX_FILES) != previous_prefix_files:
        raise RuntimeError(
            "PREFIX_FILES was not restored."
        )

    if tuple(coms.SOURCE_IMPORTS) != (
        previous_source_imports
    ):
        raise RuntimeError(
            "SOURCE_IMPORTS was not restored."
        )

    if len(processed) != 55:
        raise RuntimeError(
            f"Expected 55 processed mappings; "
            f"found {len(processed)}"
        )

    counts["source_triple_count"] = len(source_graph)
    counts["source_file_count"] = len(source_hashes)

    return processed, counts, source_graph


def build_product_records(
    processed: list[coms.ProcessedRow],
) -> tuple[
    dict[str, list[dict[str, Any]]],
    dict[str, int],
]:
    records = {
        key: []
        for key in PRODUCT_ORDER
    }

    category_counts: Counter[str] = Counter()
    row_ids: set[str] = set()
    axiom_ids: set[str] = set()

    for item in processed:
        audit = item.identity_audit

        if audit is None:
            raise RuntimeError(
                f"{item.row.diagnostic_id}: "
                "missing canonical identity audit"
            )

        if len(audit.authoritative_axioms) != 1:
            raise RuntimeError(
                f"{item.row.diagnostic_id}: expected "
                "one authoritative axiom"
            )

        identity = audit.authoritative_axioms[0]
        canonical = (
            coms.canonical_input_for_processed_row(
                item
            )
        )

        axiom_input = (
            axiom_input_from_canonical_row(
                identity,
                canonical,
            )
        )

        category = classify_target_category(
            axiom_input
        )

        try:
            product_key = CATEGORY_TO_PRODUCT[
                category
            ]
        except KeyError as exc:
            raise RuntimeError(
                f"Unsupported target category: "
                f"{category}"
            ) from exc

        row_id = item.row.stable_row_id
        axiom_id = f"sha256:{identity.sha256}"

        if row_id in row_ids:
            raise RuntimeError(
                f"Duplicate active RowID: {row_id}"
            )

        if axiom_id in axiom_ids:
            raise RuntimeError(
                "Duplicate authoritative axiom ID: "
                f"{axiom_id}"
            )

        row_ids.add(row_id)
        axiom_ids.add(axiom_id)
        category_counts[category] += 1

        records[product_key].append(
            {
                "row_id": row_id,
                "subject": item.row.subject_text,
                "category": category,
                "axiom_id": axiom_id,
                "rendered_lines": tuple(
                    modular_products
                    .render_authoritative_axiom_lines(
                        canonical,
                        axiom_id,
                    )
                ),
            }
        )

    actual_categories = dict(category_counts)

    if actual_categories != EXPECTED_CATEGORY_COUNTS:
        raise RuntimeError(
            "Unexpected SOSA-next category partition.\n"
            f"Expected: {EXPECTED_CATEGORY_COUNTS}\n"
            f"Actual:   {actual_categories}"
        )

    if len(row_ids) != 55 or len(axiom_ids) != 55:
        raise RuntimeError(
            "Expected 55 unique active RowIDs and "
            "55 unique authoritative axiom IDs."
        )

    return records, actual_categories


def body_bytes(
    records: list[dict[str, Any]],
) -> bytes:
    blocks = [
        "\n".join(record["rendered_lines"])
        for record in sorted(
            records,
            key=lambda value: value["axiom_id"],
        )
    ]

    if not blocks:
        return b""

    return (
        "\n\n".join(blocks).rstrip() + "\n"
    ).encode("utf-8")


def logical_graph(
    graph: Graph,
    ontology_iri: str,
) -> Graph:
    ontology = URIRef(ontology_iri)
    result = Graph()

    for triple in graph:
        if triple[0] != ontology:
            result.add(triple)

    return result


def serialize_product(
    metadata: Any,
    product_key: str,
    records: list[dict[str, Any]],
) -> tuple[bytes, Graph, dict[str, Any]]:
    spec = PRODUCT_SPECS[product_key]

    observed_categories = {
        record["category"]
        for record in records
    }

    if not observed_categories <= spec["categories"]:
        raise RuntimeError(
            f"{product_key}: prohibited categories "
            f"{sorted(observed_categories - spec['categories'])}"
        )

    if len(records) != spec["axiom_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['axiom_count']} axioms; "
            f"found {len(records)}"
        )

    body = body_bytes(records)
    body_hash = sha256_bytes(body)

    if body_hash != spec["body_sha256"]:
        raise RuntimeError(
            f"{product_key}: axiom-body hash mismatch\n"
            f"Expected: {spec['body_sha256']}\n"
            f"Actual:   {body_hash}"
        )

    header = (
        publication_metadata
        .render_ontology_header_bytes(
            metadata,
            product_key,
            spec["imports"],
            generated_notice=GENERATED_NOTICE,
            prefixes=spec["prefixes"],
        )
    )

    serialized = (
        header
        if not body
        else header + b"\n" + body
    )

    issues = (
        publication_metadata
        .validate_serialized_ontology_header(
            serialized,
            metadata,
            product_key,
            spec["imports"],
            generated_notice=GENERATED_NOTICE,
            prefixes=spec["prefixes"],
        )
    )

    if issues:
        rendered = "\n".join(
            (
                f"{issue.code}: {issue.field}: "
                f"{issue.message}"
            )
            for issue in issues
        )

        raise RuntimeError(
            f"{product_key}: metadata validation "
            f"failed:\n{rendered}"
        )

    graph = Graph()
    graph.parse(
        data=serialized.decode("utf-8"),
        format="turtle",
    )

    ontology = URIRef(spec["ontology_iri"])

    declarations = set(
        graph.triples(
            (None, RDF.type, OWL.Ontology)
        )
    )

    if declarations != {
        (ontology, RDF.type, OWL.Ontology)
    }:
        raise RuntimeError(
            f"{product_key}: ontology declaration "
            "mismatch"
        )

    imports = {
        str(value)
        for value in graph.objects(
            ontology,
            OWL.imports,
        )
    }

    if imports != set(spec["imports"]):
        raise RuntimeError(
            f"{product_key}: import mismatch"
        )

    if any(
        True
        for _ in graph.triples(
            (None, OWL.versionIRI, None)
        )
    ):
        raise RuntimeError(
            f"{product_key}: development product "
            "contains owl:versionIRI"
        )

    logical = logical_graph(
        graph,
        spec["ontology_iri"],
    )

    if len(logical) != spec["logical_triple_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['logical_triple_count']} "
            f"logical triples; found {len(logical)}"
        )

    if len(graph) != spec["total_triple_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['total_triple_count']} "
            f"total triples; found {len(graph)}"
        )

    product_hash = sha256_bytes(serialized)

    if product_hash != spec["sha256"]:
        raise RuntimeError(
            f"{product_key}: complete product hash "
            "mismatch\n"
            f"Expected: {spec['sha256']}\n"
            f"Actual:   {product_hash}"
        )

    result = {
        "maintained_path": spec["maintained_path"],
        "ontology_iri": spec["ontology_iri"],
        "imports": list(spec["imports"]),
        "axiom_count": len(records),
        "row_count": len(
            {
                record["row_id"]
                for record in records
            }
        ),
        "categories": sorted(
            observed_categories
        ),
        "logical_triple_count": len(logical),
        "total_triple_count": len(graph),
        "body_sha256": body_hash,
        "sha256": product_hash,
        "byte_size": len(serialized),
        "subjects": sorted(
            record["subject"]
            for record in records
        ),
        "row_ids": sorted(
            record["row_id"]
            for record in records
        ),
        "axiom_ids": sorted(
            record["axiom_id"]
            for record in records
        ),
    }

    return serialized, logical, result



def load_sosa_2023_publication_metadata() -> Any:
    """Load the governed SOSA-2023 formal-publication authority."""

    return publication_metadata.load_metadata(
        SOSA_2023_PUBLICATION_METADATA_PATH,
        product_order=PRODUCT_ORDER,
    )


def formal_product_imports(
    metadata: Any,
    product_key: str,
    context: FormalReleaseContext,
) -> tuple[str, ...]:
    """Return the exact SOSA-2023 formal ontology import contract."""

    validated_context = validate_formal_release_context(
        context
    )

    if product_key == "integrated":
        return FORMAL_INTEGRATED_EXTERNAL_IMPORTS

    if product_key == "strict_bfo_mapping":
        return ()

    if product_key == "cco_extension":
        return (
            publication_metadata.release_version_iri(
                metadata,
                "strict_bfo_mapping",
                validated_context,
            ),
        )

    raise RuntimeError(
        f"Unsupported SOSA-2023 formal product: {product_key}"
    )


def serialize_formal_product(
    metadata: Any,
    context: FormalReleaseContext,
    product_key: str,
    records: list[dict[str, Any]],
) -> tuple[bytes, Graph, dict[str, Any]]:
    """Render one immutable-context SOSA-2023 product in memory."""

    validated_context = validate_formal_release_context(
        context
    )

    spec = PRODUCT_SPECS[product_key]

    observed_categories = {
        record["category"]
        for record in records
    }

    if not observed_categories <= spec["categories"]:
        raise RuntimeError(
            f"{product_key}: prohibited formal categories "
            f"{sorted(observed_categories - spec['categories'])}"
        )

    if len(records) != spec["axiom_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['axiom_count']} formal axioms; "
            f"found {len(records)}"
        )

    body = body_bytes(records)
    body_hash = sha256_bytes(body)

    if body_hash != spec["body_sha256"]:
        raise RuntimeError(
            f"{product_key}: formal axiom-body hash mismatch\n"
            f"Expected: {spec['body_sha256']}\n"
            f"Actual:   {body_hash}"
        )

    imports = formal_product_imports(
        metadata,
        product_key,
        validated_context,
    )

    header = (
        publication_metadata
        .render_ontology_header_bytes(
            metadata,
            product_key,
            imports,
            generated_notice=FORMAL_GENERATED_NOTICE,
            prefixes=spec["prefixes"],
            context=validated_context,
        )
    )

    serialized = (
        header
        if not body
        else header + b"\n" + body
    )

    issues = (
        publication_metadata
        .validate_serialized_ontology_header(
            serialized,
            metadata,
            product_key,
            imports,
            generated_notice=FORMAL_GENERATED_NOTICE,
            prefixes=spec["prefixes"],
            mode="release",
            context=validated_context,
        )
    )

    if issues:
        rendered = "\n".join(
            (
                f"{issue.code}: {issue.field}: "
                f"{issue.message}"
            )
            for issue in issues
        )

        raise RuntimeError(
            f"{product_key}: formal metadata validation "
            f"failed:\n{rendered}"
        )

    graph = Graph()
    graph.parse(
        data=serialized.decode("utf-8"),
        format="turtle",
    )

    logical = (
        publication_metadata
        .strip_emitted_ontology_header(
            graph,
            metadata,
            product_key,
            imports,
            validated_context,
        )
    )

    if len(logical) != spec["logical_triple_count"]:
        raise RuntimeError(
            f"{product_key}: expected "
            f"{spec['logical_triple_count']} formal logical "
            f"triples; found {len(logical)}"
        )

    formal_metadata_count = len(
        publication_metadata.ontology_metadata_triples(
            metadata,
            product_key,
            validated_context,
        )
    )

    if formal_metadata_count != 10:
        raise RuntimeError(
            f"{product_key}: expected 10 formal ontology "
            f"metadata annotations; found {formal_metadata_count}"
        )

    expected_total = (
        spec["logical_triple_count"]
        + 1
        + len(imports)
        + formal_metadata_count
    )

    if len(graph) != expected_total:
        raise RuntimeError(
            f"{product_key}: expected {expected_total} formal "
            f"triples; found {len(graph)}"
        )

    if b"sosa-next" in serialized:
        raise RuntimeError(
            f"{product_key}: formal serialization retains "
            "the temporary sosa-next development identity"
        )

    product_hash = sha256_bytes(serialized)

    result = {
        "product_key": product_key,
        "stable_ontology_iri": (
            next(
                product.stable_ontology_iri
                for product in metadata.products
                if product.key == product_key
            )
        ),
        "version_iri": (
            publication_metadata.release_version_iri(
                metadata,
                product_key,
                validated_context,
            )
        ),
        "imports": imports,
        "axiom_count": len(records),
        "logical_triple_count": len(logical),
        "total_triple_count": len(graph),
        "body_sha256": body_hash,
        "sha256": product_hash,
        "byte_size": len(serialized),
        "serialized_bytes": serialized,
        "logical_graph": logical,
    }

    return serialized, logical, result


def render_formal_product_set(
    processed: list[coms.ProcessedRow],
    context: FormalReleaseContext,
    *,
    reverse_input: bool = False,
) -> dict[str, Any]:
    """Render all three SOSA-2023 formal products without writing them."""

    validated_context = validate_formal_release_context(
        context
    )

    metadata = load_sosa_2023_publication_metadata()

    records, categories = build_product_records(
        processed
    )

    products: dict[str, dict[str, Any]] = {}
    logical_graphs: dict[str, Graph] = {}

    for product_key in PRODUCT_ORDER:
        if product_key == "integrated":
            supplied = [
                *records["strict_bfo_mapping"],
                *records["cco_extension"],
            ]
        else:
            supplied = list(records[product_key])

        if reverse_input:
            supplied = list(reversed(supplied))

        _, logical, result = serialize_formal_product(
            metadata,
            validated_context,
            product_key,
            supplied,
        )

        products[product_key] = result
        logical_graphs[product_key] = logical

    modular_union = Graph()

    for product_key in MODULAR_PRODUCT_ORDER:
        for triple in logical_graphs[product_key]:
            modular_union.add(triple)

    modular_sum = sum(
        len(logical_graphs[product_key])
        for product_key in MODULAR_PRODUCT_ORDER
    )

    if modular_sum != 277 or len(modular_union) != 277:
        raise RuntimeError(
            "Expected 277 SOSA-2023 formal modular logical "
            f"triples; sum={modular_sum}, "
            f"distinct={len(modular_union)}"
        )

    if not isomorphic(
        modular_union,
        logical_graphs["integrated"],
    ):
        raise RuntimeError(
            "The formal BFO+CCO modular union differs from "
            "the formal Integrated logical graph."
        )

    return {
        "context": validated_context,
        "metadata": metadata,
        "category_counts": categories,
        "products": products,
        "combined_logical_triple_count": len(
            modular_union
        ),
        "logical_union_isomorphic": True,
    }


def build_ro_development_product(
    output_dir: Path,
) -> tuple[
    Path,
    Graph,
    dict[str, Any],
]:
    """Build the governed RO mapping for development-product checks."""

    product, active, serialized = (
        ro_generator.build()
    )

    if product["key"] != "ro_mapping":
        raise RuntimeError(
            "RO generator returned unexpected "
            f"product key: {product['key']!r}"
        )

    filename = Path(
        product["output_path"]
    ).name

    if filename != "sosa-ro-mapping.ttl":
        raise RuntimeError(
            "RO product filename differs from "
            "the governed development path: "
            f"{filename!r}"
        )

    candidate_path = (
        output_dir
        / filename
    )

    candidate_path.write_bytes(
        serialized
    )

    graph = Graph()
    graph.parse(
        data=serialized.decode(
            "utf-8"
        ),
        format="turtle",
    )

    subproperty = URIRef(
        "http://www.w3.org/"
        "2000/01/rdf-schema#"
        "subPropertyOf"
    )

    logical = Graph()

    for triple in graph.triples(
        (
            None,
            subproperty,
            None,
        )
    ):
        logical.add(triple)

    if (
        len(active)
        != product[
            "logical_triple_count"
        ]
    ):
        raise RuntimeError(
            "RO governed active-row count "
            "differs from its logical contract"
        )

    if (
        len(logical)
        != product[
            "logical_triple_count"
        ]
    ):
        raise RuntimeError(
            "RO candidate logical triple "
            "count differs from governed "
            "product contract"
        )

    if (
        len(graph)
        != product[
            "total_triple_count"
        ]
    ):
        raise RuntimeError(
            "RO candidate total triple "
            "count differs from governed "
            "product contract"
        )

    if any(
        True
        for _ in graph.triples(
            (
                None,
                OWL.imports,
                None,
            )
        )
    ):
        raise RuntimeError(
            "RO development mapping "
            "must remain import-free"
        )

    return (
        candidate_path,
        logical,
        {
            "maintained_path":
                product[
                    "output_path"
                ],
            "ontology_iri":
                product[
                    "stable_ontology_iri"
                ],
            "imports": [],
            "axiom_count":
                len(active),
            "row_count":
                len(active),
            "governed_row_count":
                product[
                    "governed_property_count"
                ],
            "no_direct_mapping_count":
                product[
                    "no_direct_mapping_count"
                ],
            "skos_mapping_count": 0,
            "logical_triple_count":
                len(logical),
            "total_triple_count":
                len(graph),
            "sha256":
                sha256_bytes(
                    serialized
                ),
            "byte_size":
                len(serialized),
            "subjects":
                sorted(
                    {
                        str(subject)
                        for (
                            subject,
                            _predicate,
                            _target,
                        ) in logical
                    }
                ),
            "candidate_path":
                str(candidate_path),
        },
    )


def build_candidate(
    output_dir: Path,
    *,
    reverse_input: bool = False,
) -> dict[str, Any]:
    output_dir = output_dir.resolve()
    shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    validate_current_sosa_products()

    metadata = build_publication_metadata()

    processed, counts, _ = process_active_rows(
        output_dir
    )

    records, categories = build_product_records(
        processed
    )

    products: dict[str, dict[str, Any]] = {}
    logical_graphs: dict[str, Graph] = {}
    product_paths: dict[str, Path] = {}

    for product_key in PRODUCT_ORDER:
        if product_key == "integrated":
            supplied = [
                *records["strict_bfo_mapping"],
                *records["cco_extension"],
            ]
        else:
            supplied = records[product_key]

        if reverse_input:
            supplied = list(reversed(supplied))

        serialized, logical, result = (
            serialize_product(
                metadata,
                product_key,
                supplied,
            )
        )

        path = (
            output_dir
            / PRODUCT_SPECS[product_key]["filename"]
        )

        path.write_bytes(serialized)

        product_paths[product_key] = path
        logical_graphs[product_key] = logical
        products[product_key] = {
            **result,
            "candidate_path": str(path),
        }

    (
        ro_path,
        ro_logical,
        ro_result,
    ) = build_ro_development_product(
        output_dir
    )

    product_paths[
        "ro_mapping"
    ] = ro_path

    logical_graphs[
        "ro_mapping"
    ] = ro_logical

    products[
        "ro_mapping"
    ] = ro_result

    combined = Graph()

    for product_key in MODULAR_PRODUCT_ORDER:
        for triple in logical_graphs[product_key]:
            combined.add(triple)

    summed = sum(
        len(logical_graphs[product_key])
        for product_key in MODULAR_PRODUCT_ORDER
    )

    if summed != 277 or len(combined) != 277:
        raise RuntimeError(
            "Expected 277 modular logical triples; "
            f"sum={summed}, distinct={len(combined)}"
        )

    reference_path = (
        output_dir / "active-mappings-reference.ttl"
    )

    reference = (
        mapping_checker.render_active_ontology(
            processed,
            reference_path,
        )
    )

    reference_logical = logical_graph(
        reference,
        str(mapping_checker.ONTOLOGY_IRI),
    )

    if len(reference_logical) != 277:
        raise RuntimeError(
            "Expected 277 integrated logical triples; "
            f"found {len(reference_logical)}"
        )

    if not isomorphic(
        combined,
        reference_logical,
    ):
        raise RuntimeError(
            "The modular product union differs from "
            "the integrated active mapping graph."
        )

    if not isomorphic(
        logical_graphs["integrated"],
        reference_logical,
    ):
        raise RuntimeError(
            "The maintained Integrated product differs "
            "from the integrated active mapping graph."
        )

    summary = {
        **counts,
        "canonical_authoritative_axiom_count": 55,
        "category_counts": categories,
        "combined_logical_triple_count": len(
            combined
        ),
        "integrated_reference_logical_triple_count": (
            len(reference_logical)
        ),
        "logical_union_isomorphic": True,
        "resolver_state_restored": True,
        "current_sosa_products_unchanged": True,
        "products": products,
        "product_paths": {
            key: str(path)
            for key, path in product_paths.items()
        },
    }

    (output_dir / "candidate-summary.json").write_text(
        json.dumps(
            summary,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    return summary


def compare_candidate_builds(
    first: Mapping[str, Any],
    second: Mapping[str, Any],
) -> None:
    for product_key in DEVELOPMENT_PRODUCT_ORDER:
        first_path = Path(
            first["product_paths"][product_key]
        )
        second_path = Path(
            second["product_paths"][product_key]
        )

        if first_path.read_bytes() != (
            second_path.read_bytes()
        ):
            raise RuntimeError(
                f"{product_key}: independent "
                "candidate builds differ"
            )


def build_reasoning_closure(
    serialized_products: tuple[bytes, ...],
    *,
    include_target_dependency: bool,
) -> Graph:
    dependencies = [
        *mapping_checker.SOURCE_FILES,
    ]

    if include_target_dependency:
        dependencies.insert(
            0,
            mapping_checker.TARGET_CCO,
        )

    return (
        modular_products
        .build_fixed_validation_closure(
            serialized_products,
            dependencies,
        )
    )


def reason_products(
    candidate: Mapping[str, Any],
    output_dir: Path,
    robot_path: str | None,
) -> dict[str, Any]:
    robot = mapping_checker.resolve_robot(
        robot_path
    )

    paths = {
        key: Path(
            candidate["product_paths"][key]
        )
        for key in PRODUCT_ORDER
    }

    serialized = {
        key: path.read_bytes()
        for key, path in paths.items()
    }

    profiles = {
        "integrated": build_reasoning_closure(
            (
                serialized["integrated"],
            ),
            include_target_dependency=True,
        ),
        "strict_bfo_mapping": build_reasoning_closure(
            (
                serialized["strict_bfo_mapping"],
            ),
            include_target_dependency=True,
        ),
        "cco_extension": build_reasoning_closure(
            (
                serialized["cco_extension"],
                serialized["strict_bfo_mapping"],
            ),
            include_target_dependency=True,
        ),
    }

    reasoning_root = output_dir / "reasoning"
    reasoning_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    results: dict[str, Any] = {}

    for product_key in PRODUCT_ORDER:
        closure = profiles[product_key]

        if any(
            True
            for _ in closure.triples(
                (None, OWL.imports, None)
            )
        ):
            raise RuntimeError(
                f"{product_key}: fixed validation "
                "closure retains owl:imports"
            )

        closure_path = (
            reasoning_root
            / f"{product_key}-closure.ttl"
        )
        reasoned_path = (
            reasoning_root
            / f"{product_key}-reasoned.ttl"
        )
        unsat_path = (
            reasoning_root
            / f"{product_key}-unsatisfiable.ttl"
        )

        closure.serialize(
            closure_path,
            format="turtle",
        )

        result = mapping_checker.run_reasoner(
            robot,
            closure_path,
            reasoned_path,
            unsat_path,
        )

        if not result["passed"]:
            raise RuntimeError(
                f"{product_key}: HermiT validation "
                f"failed: {result}"
            )

        if result["unsatisfiable_classes"]:
            raise RuntimeError(
                f"{product_key}: unexpected "
                "unsatisfiable classes: "
                f"{result['unsatisfiable_classes']}"
            )

        results[product_key] = {
            **result,
            "closure_triple_count": len(closure),
            "closure_path": str(closure_path),
        }

    return results


def run_transaction(
    output_dir: Path,
    robot_path: str | None = None,
) -> dict[str, Any]:
    output_dir = output_dir.resolve()
    shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    before = validate_current_sosa_products()

    first = build_candidate(
        output_dir / "build-a",
    )

    second = build_candidate(
        output_dir / "build-b",
        reverse_input=True,
    )

    compare_candidate_builds(first, second)

    reasoning = reason_products(
        first,
        output_dir,
        robot_path,
    )

    after = validate_current_sosa_products()

    if before != after:
        raise RuntimeError(
            "A current-SOSA maintained product "
            "changed during generation."
        )

    summary = {
        **first,
        "independent_builds_byte_identical": True,
        "reasoning": reasoning,
        "current_sosa_products_unchanged": True,
    }

    (output_dir / "transaction-summary.json").write_text(
        json.dumps(
            summary,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    return summary


def maintained_products_are_fresh(
    candidate: Mapping[str, Any],
) -> bool:
    for product_key in DEVELOPMENT_PRODUCT_ORDER:
        destination = MAINTAINED_PRODUCTS[
            product_key
        ]

        if not destination.is_file():
            return False

        candidate_path = Path(
            candidate["product_paths"][
                product_key
            ]
        )

        if (
            destination.read_bytes()
            != candidate_path.read_bytes()
        ):
            return False

    if any(
        path.exists()
        for path in RETIRED_MAINTAINED_PRODUCTS
    ):
        return False

    return True


def replace_outputs_atomically(
    candidate_paths: Mapping[str, Path],
    destinations: Mapping[str, Path],
    *,
    transaction_dir: Path,
    post_replace: Callable[[], None] | None = None,
) -> None:
    product_order = tuple(
        candidate_paths
    )

    if (
        set(product_order)
        != set(destinations)
    ):
        raise RuntimeError(
            "candidate and destination "
            "product keys differ"
        )

    backup_dir = transaction_dir / "backups"
    staging_dir = transaction_dir / "staging"

    backup_dir.mkdir(
        parents=True,
        exist_ok=True,
    )
    staging_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    backups: dict[str, Path] = {}
    originally_missing: set[str] = set()
    staged: dict[str, Path] = {}

    for product_key in product_order:
        destination = destinations[product_key]

        if destination.exists():
            backup = backup_dir / product_key
            shutil.copy2(destination, backup)
            backups[product_key] = backup
        else:
            originally_missing.add(product_key)

        stage = staging_dir / product_key
        shutil.copy2(
            candidate_paths[product_key],
            stage,
        )
        staged[product_key] = stage

    try:
        for product_key in product_order:
            destination = destinations[product_key]
            destination.parent.mkdir(
                parents=True,
                exist_ok=True,
            )

            os.replace(
                staged[product_key],
                destination,
            )

        if post_replace is not None:
            post_replace()
    except Exception:
        for product_key in product_order:
            destination = destinations[product_key]

            if product_key in backups:
                destination.parent.mkdir(
                    parents=True,
                    exist_ok=True,
                )
                shutil.copy2(
                    backups[product_key],
                    destination,
                )
            elif (
                product_key in originally_missing
                and destination.exists()
            ):
                destination.unlink()

        raise


def write_maintained_products(
    robot_path: str | None = None,
) -> dict[str, Any]:
    build_root = REPO_ROOT / "build"
    build_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    with tempfile.TemporaryDirectory(
        prefix=".sosa-next-products-",
        dir=build_root,
    ) as temporary:
        transaction_dir = Path(temporary)

        summary = run_transaction(
            transaction_dir,
            robot_path,
        )

        candidate_paths = {
            key: Path(
                summary["product_paths"][key]
            )
            for key in DEVELOPMENT_PRODUCT_ORDER
        }

        retired_bytes = {
            path: path.read_bytes()
            for path in RETIRED_MAINTAINED_PRODUCTS
            if path.is_file()
        }

        def finalize_migration() -> None:
            for path in RETIRED_MAINTAINED_PRODUCTS:
                path.unlink(missing_ok=True)

            if not maintained_products_are_fresh(
                summary
            ):
                raise RuntimeError(
                    "Maintained SOSA-next products differ "
                    "from the validated candidate build or "
                    "a retired product remains materialized."
                )

        try:
            replace_outputs_atomically(
                candidate_paths,
                MAINTAINED_PRODUCTS,
                transaction_dir=transaction_dir,
                post_replace=finalize_migration,
            )
        except Exception:
            for path, payload in retired_bytes.items():
                path.parent.mkdir(
                    parents=True,
                    exist_ok=True,
                )
                path.write_bytes(payload)
            raise

        if not maintained_products_are_fresh(
            summary
        ):
            raise RuntimeError(
                "Maintained SOSA-next products differ "
                "from the validated candidate build."
            )

        summary["maintained_write"] = True

        return summary


def check_maintained_products(
    output_dir: Path,
    robot_path: str | None = None,
) -> dict[str, Any]:
    summary = run_transaction(
        output_dir,
        robot_path,
    )

    fresh = maintained_products_are_fresh(
        summary
    )

    result = {
        **summary,
        "maintained_products_fresh": fresh,
        "passed": fresh,
    }

    (output_dir / "check-summary.json").write_text(
        json.dumps(
            result,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    return result


def print_summary(summary: Mapping[str, Any]) -> None:
    print(
        "Governed rows: "
        f"{summary['governed_row_count']}"
    )
    print(
        "Active mappings: "
        f"{summary['active_mapping_count']}"
    )
    print(
        "Deferred mappings: "
        f"{summary['deferred_mapping_count']}"
    )
    print(
        "No-direct-mapping decisions: "
        f"{summary['no_direct_mapping_row_count']}"
    )
    print(
        "Unreviewed rows: "
        f"{summary['unreviewed_row_count']}"
    )
    print(
        "Legacy explicitly unmapped aggregate: "
        f"{summary['explicitly_unmapped_row_count']}"
    )
    print(
        "Canonical authoritative axioms: "
        f"{summary['canonical_authoritative_axiom_count']}"
    )
    print(
        "Target categories: "
        f"{summary['category_counts']}"
    )
    print(
        "Combined logical triples: "
        f"{summary['combined_logical_triple_count']}"
    )

    for product_key in PRODUCT_ORDER:
        product = summary["products"][
            product_key
        ]
        reasoning = summary["reasoning"][
            product_key
        ]

        print(f"{product_key}:")
        print(
            f"  axioms: "
            f"{product['axiom_count']}"
        )
        print(
            f"  logical triples: "
            f"{product['logical_triple_count']}"
        )
        print(
            f"  total triples: "
            f"{product['total_triple_count']}"
        )
        print(
            f"  SHA-256: "
            f"{product['sha256']}"
        )
        print(
            "  reasoning closure triples: "
            f"{reasoning['closure_triple_count']}"
        )
        print(
            "  unsatisfiable classes: "
            f"{len(reasoning['unsatisfiable_classes'])}"
        )

    ro_product = summary[
        "products"
    ].get(
        "ro_mapping"
    )

    if ro_product is not None:
        print("ro_mapping:")
        print(
            "  axioms: "
            f"{ro_product['axiom_count']}"
        )
        print(
            "  governed properties: "
            f"{ro_product['governed_row_count']}"
        )
        print(
            "  no direct mapping: "
            f"{ro_product['no_direct_mapping_count']}"
        )
        print(
            "  logical triples: "
            f"{ro_product['logical_triple_count']}"
        )
        print(
            "  total triples: "
            f"{ro_product['total_triple_count']}"
        )
        print(
            "  SHA-256: "
            f"{ro_product['sha256']}"
        )
        print(
            "  SKOS mappings: "
            f"{ro_product['skos_mapping_count']}"
        )
        print(
            "  reasoning: dedicated "
            "SOSA-2023 RO semantic regression"
        )



def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__
    )

    parser.add_argument(
        "--output-dir",
        default=(
            "/tmp/sosa-next-product-generation"
        ),
        help=(
            "Directory for candidate and validation "
            "evidence."
        ),
    )

    parser.add_argument(
        "--robot",
        help="Optional explicit ROBOT executable path.",
    )

    parser.add_argument(
        "--write-maintained",
        action="store_true",
        help=(
            "Atomically replace all maintained "
            "SOSA-next products after all gates pass."
        ),
    )

    args = parser.parse_args(argv)

    try:
        if args.write_maintained:
            summary = write_maintained_products(
                args.robot
            )
        else:
            summary = run_transaction(
                Path(args.output_dir),
                args.robot,
            )
    except Exception as exc:
        print(
            "SOSA-next product generation: FAIL"
        )
        print(exc)
        return 1

    print_summary(summary)

    if args.write_maintained:
        print(
            "Maintained SOSA-next products: UPDATED"
        )
    else:
        print(
            "Candidate SOSA-next products: PASS"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
