name: Test SSN/SOSA and SOSA-Only BFO/CCO Mapping Changes

on:
  pull_request:
    branches:
      - main
      - dev
      - tests
  workflow_dispatch:

env:
  cache-path: build/lib
  artifacts-path: src/**/build/artifacts/
  cache-key: build-cache-dependencies

jobs:
  ontology_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cached dependencies
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.cache-path }}
          key: ${{ runner.os }}-${{ env.cache-key }}

      - name: Validate current SSN/SOSA mappings
        run: make -C src current-ssn-sosa

      - name: Validate forthcoming SOSA-only mappings
        run: make -C src sosa-next
        if: always()

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ontology_test_results
          path: ${{ env.artifacts-path }}

      - name: Save dependencies to cache
        id: save-cache
        uses: actions/cache/save@v3
        if: always() && steps.restore-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.cache-path }}
          key: ${{ runner.os }}-${{ env.cache-key }}
